import type { Metadata } from "next";
import { Urbanist } from "next/font/google"
import "./globals.css";
import { Navbar } from "@/components/navbar";
import Footer from "@/components/footer";
import { ThemeProvider } from "@/components/theme-provider";
import { UserProvider } from "@auth0/nextjs-auth0/client";

const urbanist = Urbanist({
    subsets: ["latin"]
});

export const metadata: Metadata = {
  title: "Ecom-demo",
  description: "Generated by Lopez Gaitan Fede ",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" >
      <UserProvider>
      <body
        className={`${urbanist.className} antialiased`} >
        <ThemeProvider
         attribute="class"
         defaultTheme="system"
         enableSystem
         disableTransitionOnChange>
        <Navbar/>
        {children}
        <Footer/>
        </ThemeProvider>
      </body>
       </UserProvider>
    </html>
  );
}
